#!/bin/sh
# oxr 2025
# Chequeo de opciones
#
# \\b    check [-] texto && ... || ...
#
# '-' si 'check' fue incluido en el programa, no lo termina al pulsar [q].

# Una llamada directa desde bash sin '-' ¡cerrara el terminal!
# Las acciones son [s]si [enter]no [q]quitar/cancelar
# La salida, se recoge con '$?' ,si>0 enter>1 cancelar>2 quitar>3


[ $include_ctl ] || . include ; include parp


check_E(){
local sp="¬" # separador para parp
[ ${#2} -ne 0 ] && check_T="$check_T $sp :" || check_T="^ $check_T $sp , -"
parp -s $sp $check_T -z -c 74 [$1] $sp +- 2
}


check(){
[ ${#1} -eq 0 ] && infsh ~/code/check 3 11 && return 2 || :
local check_T="$@" check_R="" check_Q=true
[ "$1" != "-" ] || { shift ; check_Q=false; }
check_E s -
read check_R
case $check_R in
	s) check_E s ; return 0 ;;
	q) check_E q ; $check_Q && exit 3 || return 2 ;;
	*) check_E " " ; return 1 ;;
esac
}


[ ${0##*/} != check ] || check "$@"
#
