#!/bin/sh
#acuku_code oxr 2026

# Include this file in your .bashrc
# user$ echo ". PATH_TO/code.conf" >> /home/$USER/.bashrc

# By default, these scripts are expected to be in the /home/$USER/code folder,
# since 'include', 'tempfreq_log' and each script's calls to 'infsh' all refer to
# this folder:

# Define your prefered path, is same "PATH_TO":
readonly code=~/code

PATH=$code:$PATH

# Some tools' working files are located in /tmp/code_$USER, and others use
# /tmp/code_$USER/vacio to operate with wildcards [*|?] without incident.
readonly tmp=/tmp/code_$USER

[ -e /$tmp/vacio ] || {
mkdir $tmp
mkdir -m a-w $tmp/vacio
}

# Also some tools use variables $T $E $R as 'tab' 'esc' and 'new line' characters,
# $tmp as temp folder and $code as path to code:
export PATH code tmp E='\e' T='	' R='
'
# Not modify R value, it is good. Because this export not's permited local
# variables with these names, and globally code and tmp. PATH is a system var.

# This include the suite in your terminal
. include varize check infsh rand mt killer
