#!/bin/sh
#oxr 2025
# gestion de salida del sistema o ejecuta una orden, por tiempo o temperatura
#
# \\r    fin [[-+]t [nº]] [[-p]oweroff | [-h]ibernate | [-s]leep | [-r]eboot | [orden]]
#
# '-t|+t' cuando la temperatura baje o suba hasta nº, sino en nº o 300 segundos
# '-[p|h|s|r]' accion a realizar, sino hibernate
#


[ "$USER" = "root" ] || { su - root -c "exec $0 $*" ; return ;}

PATH=$code:$PATH
[ $include_ctl ] || . include ; include varize tize # isnum - varize incluye enum y este isnum


fin(){
local a="" t="" g="" c="" d="/sys/class/thermal/thermal_zone0/temp" r="" o="-le" x=false
# a accion - t tiempo - g grados - c texto - d dirtemp - r read - o operador
[ $# -eq 0 ] && { infsh $code/fin 3 8 ; return 1 ;} || {
while [ $# -ne 0 ] ; do case $1 in
-t) isnum $2 && { g=$2 ; shift 2 ;} || { g=40 ; shift ;} ;;
+t) isnum $2 && { g=$2 ; o="-ge" ; shift 2 ;} || { g=70 ; shift ;} ;;
-p)a=poweroff ; break ;;
-h)a=hibernate ; break ;;
-s)a=sleep ; break ;;
-r)a=reboot ; break ;;
-c) shift ; a=$@ x=true ; break ;;
*) [ ${#t} -ne 0 ] && break || { isnum $1 && { t=$1 ; shift ;} || { infsh $code/fin 3 8 ; return 1 ;} } ;;
esac ; done
}

[ ${#a} -ne 0 ] || a=reboot

[ ${#g} -eq 0 ] && {
	[ ${#t} -ne 0 ] || t=3
	c="En $t segundos"
} || {
	read r < $d
	r=$((r/1000)) ; unset $t
	[ $o = "-le" ] && c="baje" || c="suba"
	c="Cuando Tªactual($rº) $c a $gº"
}

tize -e -c 75 $t / -c 6 $a / -c 2 [s / -c 2 ] / -c 17 $gº / -c 71 $rº / -c 9 -p ... / "$c $a ..." # Esta seguro[s]"
# read c
# [ "$c" = "s" ] || exit 0

[ ${#g} -ne 0 ] && {
	until [ $r $o $g ] ; do
		sleep 30
		read r < $d
		r=$((r/1000))
		echo 'M[17G[1;97;41m'$rº'[0m'
	done
	echo "$a en 3 segundos"'[1;5m' ...'[0m'
	sleep 3
	echo 'M['$((${#a}+16))G ...'[0m'
} || sleep $t

[ ! -e /tmp/wifi.ctl ] || { wifi D ; rm /tmp/wifi.ctl ;}
sync
fm -
#umount -a 2>/dev/null
$x && $a || systemctl start $a.target
return 0
}


[ ${0##*/} != fin ] || fin "$@"
#
