#!/bin/sh
#oxr 2025
# Estiliza la cabecera de un script, por defecto da color a algunos objetivos
# pero se pueden indicar otros
#
# \\r	infsh archivo inicio fin [[estilo] objetivo SEP [estilo] objetivo ... ]
#
# 'archivo'    del que leer la cabecera
# 'inicio fin' lineas a mostrar
# 'estilo'     [-c 0-7|00-77 con fondo] [-b] bold [-p] parpadeo [-u] subrayado
# 'objetivo'   a colorear. "Entrecomillar", o escapar caracteres especiales '⧵c'
# 'SEP'        '¬' separador de instancias.
#
# '[]' opcional, '{}' opcionales relacionadas, '()' obligatorias excluyentes
# '|'  alternativa, ··· continua instruccion, ... mas instancias
# '⧵ ∕' caracteres para suplantar barras invertidas si necesario
# '⧵⧵r' hace que se respeten los espacios|tabs al inicio de un comentario
#


[ $include_ctl ] || . include ; include tb shead


infsh(){
[ ${#3} -eq 0 ] && { infsh ~/code/infsh 3 17 ; return ;}
local a=$1 i=$2 f=$3 o=""
shift 3
[ $# -eq 0 ] || o="$@ ¬"
shead -n -a $a $i $f -p - \# | tb tize -s ¬ -c 3 "[" ¬ -c 3 "]" ¬ -c 2 \" ¬ -c 2 "'" ¬ -c 7 $ ¬ -c 6 "º" ¬ -c 6 "+" ¬ -c 6 "-" ¬ -c 6 "=" ¬ -c 5 "<" ¬ -c 5 ">" ¬ -c 5 "{" ¬ -c 5 "}" ¬ -c 4 "(" ¬ -c 4 ")" ¬ -c 6 "|"  ¬ -c 6 "&" ¬ -c 2 "···" ¬ -c 7 -u Opciones generales ¬ -c 7 -u Opciones de instancia ¬ -c 6 -b SEP ¬ -c 6 "/" ¬ -c 6 "⧵" ¬ -c 6 "∕" ¬ $o
# las dos untimas barras son sustitutas de las reales
}


[ ${0##*/} != infsh ] || infsh "$@"
#
