#!/bin/sh
# oxr 2025 SHEAD V2
# Filtra lineas por contenido o pre/sufijo, puede remarcar, borrar o reemplazar,
# contar y definir el modo de salida.
#
# \\r    (|) shead (-a archivo) [-o archivo] [-t] [-l|-C] [-S SEP] [-n] ···
# ···   [-f nº|inicioº [finº]] [-z] [-b] [-u] [-P] [-c colorº] [-p|-pp|-s|-ss] ···
# ···    [-|!] [--] filtro [-r reemplazo] [SEP nueva instancia [SEP ...]]
#
# Opciones generales:
# '-a'       lee de archivo sino de la salida standard '|', excluyentes entre si
# '-o'       salida a otro archivo
# '-t'       devolvera todas las lineas en modo pre/sufijo
# '-l'       mostrara el nº de linea
# '-C'       devolvera el nº de lineas concordantes, si '!' las resultantes; por
# \\r           pre/sufijo siempre las concordantes
# '-S'       separador, por defecto es '/'
# '-n'       sin estilo
# '-f'       filtrara las nº ultimas lineas. Ultima opcion general
# 'inicio fin' lineas a examinar, todas por defecto. Ultima opcion general
# Opciones de instancia:
# '-p|-s'    filtrara por prefijo o sufijo y actuara sobre ellos, acepta '?'
# '-pp|-ss'  idem pero actuara en toda la linea, acepta '?' y '* '
# '-|-q'     no mostrara el filtro.
# '!|-N'     no mostrara las lineas con coincidencias.
# '-c'       da color al filtro o su reemplazo, color[0-7] color/fondo[00-77]
# '-b'       no bold
# '-u'       subrayado
# '-P'       parpadeante
# '-z'       no hara saltos de linea. En la ultima instancia
# '--'       fin de opciones, puede ser necesario si filtro es un numero.
# 'filtro'   texto a encontrar. Entrecomillar si espacios o comodines
# '-r'       reemplazar por 'reemplazo'.
#
# Por defecto se muestran todas las lineas y se resaltan las coincidencias.
# Por 'pre/sufijo' se muestran las lineas con coincidencias sin resaltado. Se
# puede filtrar por contenido con '-p *filtro' o '-s filtro*' para mostrar solo
# las lineas coincidentes; si se indica color 'filtro' no puede tener comodines.
#
#(1) si el archivo tiene una sola linea sin salto de linea, read lee la linea
# y sale del bucle sin ejecutar su contenido.
#
# INCLUIBLE EN OTROS SCRIPTS '. shead'


# EN PROCESO
# Rehacer bloque pre/sufijo mostrar filtro al modo aplicado al de no mostrar,
# compartir el sistema de diferenciacion y reducir las instrucciones tize

[ $include_ctl ] || . include ; include tize isnum path


shead_fun(){
local ln="" tr="" mt=true sp="øo" ft=""
# ln nºlinea - tr texto_restante - mt mostrar - sp separador_para_tize - pt parte
[ ${#shead_ft} -eq 0 ] || { # filtrar
	[ $shead_pt = I ] && { # Contenido
		tr=${shead_tx##*$shead_ft}
		[ ${#shead_rp} -ne 0 ] || {
			[ "$shead_tx" != "$tr" ] && { # coincide
				case $shead_md in
				false) # mostrar
						[ ${#shead_cl} -ne 0 ] || shead_cl="-c 2"
						shead_nr=$((shead_nr+1))
						tize -v shead_tx -s $sp $shead_ne $shead_cl $shead_ft $sp "$shead_tx" ;;
				true) # no mostrar el filtro
						shead_nr=$((shead_nr+1))
						tize -v shead_tx -s $sp $shead_ne -q $shead_ft $sp "$shead_tx" ;;
				  "") # no mostrar lineas coincidentes
					# shead_nr=$((shead_nr+1))
					mt=false ;;
				esac
			} || { [ ${#shead_md} -ne 0 ] || shead_nr=$((shead_nr+1)) ;}
		}
	} || { # Prefijo/Sufijo
		case $shead_pt in
			P)  tr=${shead_tx#$shead_ft}   pt=${shead_tx%$tr} ;;
			PP) tr=${shead_tx##$shead_ft*} pt=${shead_tx%$tr} ;;
			S)  tr=${shead_tx%$shead_ft}   pt=${shead_tx#$tr} ;;
			SS) tr=${shead_tx%%*$shead_ft} pt=${shead_tx#$tr} ;;
		esac
		[ ${#shead_md} -ne 0 -a "$shead_tx" != "$tr" ] && { # mostrar y no mostrar filtro
			[ ${#shead_rp} -ne 0 ] || {
				shead_nr=$((shead_nr+1))
				$shead_md && shead_cl="-q" || [ ${#shead_cl} -eq 0 -o ${#shead_ne} -gt 0 ] && shead_ne="-n"
				tize -v pt -s $sp $shead_ne $shead_cl $shead_ft $sp "$pt"
				[ $shead_pt = P -o $shead_pt = PP ] && shead_tx=$pt$tr || shead_tx=$tr$pt
			}
		} || { # no mostrar lineas coincidentes - se mostraran lineas no coincidentes
			[ ${#shead_md} -eq 0 -a "$shead_tx" = "$tr" ] || { # siempre que no sean true
				[ ${#shead_md} -ne 0 ] || shead_nr=$((shead_nr+1))
				$shead_mt || mt=false
			}
		}
	}
} # Sin filtro

! $mt || { # reemplazar? y aplicar
# solo pasa si las 2 son false
[ ${#shead_rp} -eq 0 ] || [ "$shead_tx" = "${shead_tx##*$shead_ft}" ] || { # reemplazar
	[ ${#shead_cl} -ne 0 ] || { [ $shead_pt != I ] || shead_cl="-c 6" ;}
	shead_nr=$((shead_nr+1))
	[ $shead_pt = P -o $shead_pt = S ] && {
		[ ${#shead_cl} -eq 0 ] || tize -v shead_rp $shead_cl $shead_rp
# echo --$shead_rp--$tr--
		[ $shead_pt = P ] && shead_tx=$shead_rp$tr || shead_tx=$tr$shead_rp
	} || {
		[ $shead_pt != I -a ${#shead_cl} -eq 0 ] && shead_ne="-n"
		tize -v shead_tx -s $sp $shead_ne $shead_cl $shead_ft -r $shead_rp $sp "$shead_tx"
	}
}

#aplicar
$shead_nm && ! $shead_mi && ln=$shead_ct"\t" || :

shead_rs="$shead_rs$ln$shead_tx$shead_sl"
}
}


shead(){
local dp="$PWD" ae="" cm="" as="" td="" it="" sp="/" in=1 ul=0 at=$tmp/shead
# dp directorio_previo - ae archivo - cm comodin - as archivo_salida - td todo - it instancia - sp separador - in inicial - ul ultima - at archivo_temporal
shead_nm=false shead_tx="" shead_ft="" shead_rs="" shead_pt="I" shead_md=false shead_ct=0 shead_sl='\n' shead_rp=""
shead_cr=false shead_nr=0 shead_mt=false shead_ne="" shead_mi=false shead_cl=""
# nm numerar - tx texto - ft filtro - rt resultado - pt parte - md modo - ct contador - sl salto_linea - rp reemplazo - dr devolver_resultados - nr nº_resultados - mt mostrar_todo - nm numerar_lineas - mi multiinstancias - cl color - ne sin estilo
[ $# -ne 0 ] || { infsh ~/code/shead 3 38 -c 7 filtro ¬ -c 5 Ultima opcion ; return ;}

# echo "pid_orden(\$$) $$ -- orden(\$0) $0 -- nº_param(\$#) $# -- param(\$@) $@"
# echo "ultimo_param(\$_) $_ -- pid_ultimo_proc(\$!) $! -- codigo_salida(\$?) $?"

while [ $# -ne 0 ] ; do case "$1" in # opciones generales
	-a)	path ae "$2" && shift 2 || { echo "No existe el archivo $2" ; return ;} ;;
	-o) sa=true as="$2" ; shift 2 ;;
	-l) shead_nm=true ; shift ;;
	# -z) shead_sl="" ; shift ;; # movido a ops. instancias
	-n) shead_ne="-n" ; shift ;;
	-t) shead_mt=true ; shift ;;
	-S) sp="$2" ; shift 2 ;;
	-C) shead_cr=true shead_ne="-n" ; shift ;;
	-f)	[ ${#ae} -ne 0 ] && {
		while read shead_tx ; do ul=$((ul+1)) ; done < "$ae" ; in=$((ul+1-$2))
		} || {
			>$at
			while read shead_tx ; do ul=$((ul+1)) ; echo $shead_tx >> $at ; done ; in=$((ul+1-$2))
			ae=$at
		}
		shift 2 ;;
	 *)	[ ${#ae} -eq 0 -a -e "$1" ] && {
			path ae "$1" ; shift
		} || {
			isnum $1 && {
				in=$1 ; shift ; isnum $1 && { ul=$1 ; shift ; break ;}
			} || break
		} ;;
esac ; done

cd $tmp/vacio

td=$@

while : ; do #Gestion de instancias
	it=${td%% $sp *} td=${td#$it $sp }
    set -- $it
#opciones de instancia
	shead_cl=""
	while [ $# -ne 0 ] ; do case "$1" in
		!|-N) shift; shead_md="" ;;
		-|-q) shift; shead_md=true ;;
		-p) shift; shead_pt="P" ;;
		-pp) shift; shead_pt="PP" ;;
		-s) shift; shead_pt="S" ;;
		-ss) shift; shead_pt="SS" ;;
		-c) shead_cl="-c $2" ; shift 2 ;; #color
		-P) shead_cl="$shead_cl -p" ; shift ;; #parpadeo
		-u) shead_cl="$shead_cl -u" ; shift ;; #subrayado
		-b) shead_cl="$shead_cl -b" ; shift ;; #no bold
		-z) shead_sl=" " ; shift ;;
		--)shift;break;;
		*)break;;
	esac ; done
#filtro
	shead_ft=$@
	[ "$shead_ft" != "${shead_ft#* -r }" ] && { #si reemplazar
		shead_rp=${shead_ft##* -r } shead_ft=${shead_ft%% -r *} #shead_rp=$shead_ft" -r "$shead_rp
	} || { #si reemplazar por nada
		[ "$shead_ft" = "${shead_ft#* -r}" ] || shead_ft=${shead_ft%% -r} shead_rp='\b' #shead_rp=$shead_ft" -r "'\b'
	}
	[ $ul -ne 0 ] || ul=10000
#Accion
	[ ${#ae} -ne 0 ] && {
	while read shead_tx ; do
		shead_ct=$((shead_ct+1))
		[ $shead_ct -ge $in ] || continue
		shead_fun
		shead_tx="" #(1)
		[ $shead_ct -lt $ul ] || break
	done < "$ae"
	[ ! "$shead_tx" ] || shead_fun #(1)
	} || {
	while read shead_tx ; do
		shead_ct=$((shead_ct+1))
		[ $shead_ct -ge $in ] || continue
		shead_fun
		[ $shead_ct -lt $ul ] || break
	done
	}

[ "$td" != "$it" ] || break
		ae=$at in=1 shead_mi=true shead_nr=0 shead_rp="" shead_pt="I" shead_md=false shead_ct=0 shead_ft=""
		[ ${#BASH} -ne 0 ] && echo -e -n "$shead_rs" > "$ae" || echo -n "$shead_rs" > "$ae"
		shead_rs=""
done

cd "$dp"
$shead_cr && return $shead_nr || { # nº de resultados
	[ ${#as} -eq 0 ] && { # salida a pantalla
		[ ${#BASH} -ne 0 ] && echo -e -n "$shead_rs" || echo -n "$shead_rs"
	} || { # salida a archivo
		[ ${#BASH} -ne 0 ] && echo -e -n "$shead_rs" >> "$as" || echo -n "$shead_rs" >> "$as"
	}
}
}


# Evitar conflictos entre corchetes/comodines y nombres de archivo:
#	' [*nombre archivo monocaracter*] ' '?nam' 'nam?' '*nam' 'nam*'
# que provocan al ser enviados a una funcion o programa, que reciben los nombres
# de los archivos que hay en el directorio desde donde se lanzo la orden.
# SOLUCION ACTUAL
# Directorio de trabajo vacio
# mkdir -m -w -p $tmp/vacio


[ ${0##*/} != shead ] || shead "$@"


# GESTION MANUAL DE * ,reemplaza con ?[?...] - ya no hace falta
# . enum
# x=1234567
#prefijo
# y=*6?
# [ "${y#"*"}" = "$y" ] || { enum c $((${#x}-(${#y}-1))) ; y=${y#"*"} ; for i in $c ; do y='?'$y ; done ;}
# echo --"$y"--${x#$y}--
#sufijo
# y=?2*
# [ "${y%"*"}" = "$y" ] || { enum c $((${#x}-(${#y}-1))) ; y=${y%"*"} ; for i in $c ; do y=$y'?' ; done ;}
# echo --"$y"--${x%$y}--
#

#
