#!/bin/sh
# oxr 2024
# Captura la salida de una tuberia y se la entrega a un script
#
# >    orden | tb script [argumentos]
#
# Tras 'script' o 'argumentos' de darse, se colocara la salida de 'orden'.
# 'script' puede ser un comando que no recoja tuberias como echo o printf.


tb(){
local x=""
[ ${#1} -eq 0 ] || ! type $1>/dev/null && {	infsh ~/code/tb 3 8 ; return ;}
while read x ; do # lee de la tuberia
	"$@" " $x"
	echo
done
}


[ ${0##*/} != tb ] || tb "$@"
#
