#!/bin/sh
# oxr 2025
# Captura la salida de una orden o lee de un archivo, y entrega cada linea a un
# script o comando, que se ejecuta con cada linea recibida.
#
# \\b    (|) tb [-n] (-a archivo) comando [argumentos]
#
# '-n'    no 'echo' tras cada ejecucion desde tuberia
#
#
#(1) si el archivo tiene una sola linea, sin salto de linea; read lee la linea
# y sale del bucle sin ejecutar su contenido.


tb(){
local l="" a="" n=true
# echo -- $1 -- $2 -- $3 -- $4 --
[ $# -gt 0 ] || { infsh ~/code/tb 3 8 ; return ;}
[ $1 = "-n" ] && shift || n=false
[ $1 = "-a" ] && {
	a="$2" ; shift 2
	[ -e "$a" ] || { echo "No existe el archivo '$a'" ; return ;}
	[ $# -gt 0 ] || set -- echo # a falta de comando
	while read l ; do # lee de archivo
		"$@" "$l"
	done < "$a"
} || {
	while read l ; do # lee de tuberia
		"$@" "$l"
		$n || echo
	done
	}
[ ! "$l" ] || "$@" "$l" #(1)
}


[ ${0##*/} != tb ] || tb "$@"
#
