#!/bin/sh
# oxr 2025
# Da estilo, elimina ,reemplaza o cuenta ocurrencias en un texto
#
# \\r    tize [-e] [-s SEP] [-C] [-v var] (-a archivo) (-o 'orden') ···
# ···    [-n] | [[-c nº|-f nº] [-b] [-p] [-u]] ···
# ···    [(-q) objetivo (-r reemplazo)] [SEP nueva instancia...] [--] (SEP texto)
#
# Opciones generales:
# '-s'    SEParador de instancias, '/' por defecto. Antes que '-a'.
# '-C'    cuenta las coincidencias.
# '-v'    nombre de variable a asignar el resultado.
# '-a'    lee de archivo, separadores en archivo diferente al de instancias.
# '-o'    actua sobre la salida de una orden.
# '-e'    'echo' al final.
# Opciones de instancia:
# '-c|-f' formato de color y fondo: -c (0-7 ó mas fondo 00-77) -f (0-7).
# '-b'    no bold.
# '-p'    parpadeante.
# '-u'    subrayado
# '-n'    sin estilo.
# '-q'    quita ocurrencias.
# '-r'    reemplaza ocurrencias.
# '--'    fin de opciones, en caso de ser necesario.
#
# Para la asignacion a variable, incluir: '. tize'
# En 'texto', si no '-n', se colorearan todas las ocurrencias de 'objetivo' o
#  'reemplazo'. Si no se da 'color' o 'fondo' estos seran verde y normal.
# Si va a colorear un solo caracter pongalo en la primera instancia, queriendo
#  colorear mas, puede fallar, por los caracteres de las secuencias de escape
# Los abarcadores '[',']','{' y '}' cada uno en una instancia y en ese orden
# Otros caracteres especiales como '() <>' entrecomillarlos "(" o escaparlos ⧵(
#
# EN PROCESO - FUNCIONA - INCLUIBLE '. tize'.
#


[ $include_ctl ] || . include ; include sep #varize


tize_fun(){
local bd=1 cl=";92" cs=0 ct=0 ec='[' ex="" fd=";49" md="" nc=false ob="" rg="" rp=false rs="" rt="" rx=0
# bd bold - cl color - cs contador_seguridad - ct contador - ec escape_caracter - ex expandir - fd fondo - md modificacion - nc no colorear - ob objetivo - rg registro - rp reemplazar - rs resultado - rt resto - rx resto_exp

while [ ${#2} -ne 0 ] ; do case $1 in # Estilo - si no hay $2 no es una opcion, ya es texto
	-c) [ ${#2} = 1 ] && cl=";9"$2 || cl=";9"${2%?} fd=";4"${2#?} ; shift 2 ;;
	-f) fd=";4"$2 ; shift 2 ;;
	-p) fd=$fd";5" ; shift ;;
	-b) bd=0 ; shift ;;
	-u) fd=$fd";4" ; shift ;;
	-n) $nc && nc=false || nc=true ; shift ;;
	--) shift ; break ;;
	*) break ;;
esac ; done

[ ${#tize_sp} -ne 0 ] || { $nc && tize_tx=$@ || tize_tx=$ec$bd$cl$fd"m"$@$ec"0m" ; return ;} # texto simple

ob=$@ ob=${ob#-q } rt=$tize_tx rx=$tize_tx cs=${#tize_tx}

[ "$ob" != "${ob#* -r }" ] && { rp=true md=${ob##* -r } ob=${ob%% -r *} # con reemplazo
} || { [ "$ob" = "${ob#* -r}" ] || rp=true md='\b' ob=${ob%% -r} ;} #sin reemplazo '' ' ' y nada
[ "$ob" != "${ob%\?*}" ] || [ "$ob" != "${ob%\**}" ] && ex=$ob # para expansion

while [ ${#rt} -ne 0 ] ; do #aplicacion
	[ ${#ex} -eq 0 ] || ob=${rx#${rx%%$ex*}} ob=${ob%${ob##$ex}} rx=${rx#*"$ob"} # expansion objetivo
	[ ${#ob} -ne 0 ] && ct=$((ct+1)) || { [ ${#ex} -gt 0 ] && rs=$rs$rx || rs=$rs$rt ; break ;} # no mas coincidencias
	[ "$1" = "-q" ] || { # reemplazar / colorear
		$rp && { $nc || md=$ec$bd$cl$fd"m"$md$ec"0m" ;} || { $nc && md=$ob || md=$ec$bd$cl$fd"m"$ob$ec"0m" ;}
	}
	[ "${rt#"$ob"}" != "$rt" ] || { # resto no comienza con objetivo
		rg=$rg${rt%%$ob*} rs=$rs${rt%%"$ob"*} # añade texto hasta objetivo
		[ "$rg" != "$tize_tx" ] || { ct=$((ct-1)) ; break ;} # todo leido
	}
	rg=$rg$ob rs=$rs$md rt=${rt#*$ob} # añade objetivo y actualiza restante
	cs=$((cs-1)) ; [ $cs -ne -1 ] || { echo "TIZE>Fuera de control" ; break ;} # ERROR
done

$tize_ct && tize_tx=$ct || tize_tx="$rs"

}


tize(){
local tize_ae="" tize_cm="" tize_dr="$PWD" tize_ef=true tize_or="" tize_v="" tize_sl='
'
# ae archivo_entrada - cm comodin - dr dir_previo - ef no_echo_final - sl salto_de_linea - or orden - v variable_destino

tize_ct=false tize_sp="/" tize_tx="" # global
# ct contar - sp separador - tx texto

while [ $# -ne 0 ] ; do case $1 in # Generales - si no hay $2 no es una opcion, ya es texto
	-a) while read tize_cm ; do tize_ae="$tize_ae$tize_cm$tize_sl" ; done < "$2" ; shift 2 ; tize_ae=${tize_ae%$tize_sl} ; set -- "$@ $tize_sp $tize_ae" ;;
	-e) tize_ef=false ; shift ;;
	-s) tize_sp="$2" ; shift 2 ;;
	-v) tize_v="$2" ; shift 2 ;;
	-C) tize_ct=true ; shift ;;
	# -o) varize tize_or $2 ; shift 2 ; set -- "$@ $tize_sp $tize_or" ;;
	-o) $2>$tmp/tize ; while read cm ; do tize_or="$tize_or $cm$sl" ; done <$tmp/tize ; shift 2 ; set -- "$@ $tize_sp $tize_or" ;;
	*) break ;;
esac ; done

[ $# -ne 0 ] || { infsh -i $code/tize 3 32 -u objetivo ; return ;}
cd $tmp/vacio
tize_cm=$@ tize_tx=${tize_cm##* $tize_sp } # texto

[ "$tize_cm" = "$tize_tx" ] && { tize_sp="" ; tize_fun $tize_tx ;} || {  # <-texto simple
	set -- ${tize_cm% $tize_sp *} # Quita ultimo separador y el texto
	sep -s $tize_sp -O 'tize_fun $sep_C' $@
}

cd "$tize_dr"
[ ${#tize_v} -ne 0 ] && eval $tize_v='$tize_tx' || {
	[ ${#BASH} -ne 0 ] && echo -e -n "$tize_tx" || echo -n "$tize_tx"
}
$tize_ef || echo
}


# Evitar conflictos entre corchetes/comodines y nombres de archivo: ver shead
# mkdir -m -w -p $tmp/vacio


[ ${0##*/} != tize ] || tize "$@"
#
